###
GET http://localhost:3001/api/notes/


###
GET http://localhost:3001/api/notes/6583e90658c7aa6c8e32ee17

###
POST http://localhost:3001/api/notes/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NThjZjQxZGNmNjk5ZThiNzBhNmUyYTYiLCJpYXQiOjE3MDM3MzY3NjZ9.KZf1KBG1i4fttnE3-4p3ZIL-UI8tDsB-myqRymljRv8

{
    "content": "Added new content",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/6585504a629081a7502c75c5
