###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/6583ea7c8aeca505b070e711

###
DELETE http://localhost:3001/api/persons/6585450dd65c5e2b45357790

###
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "name": "Jerry",
    "number": "023-123123"
}
